" Import the shared configuration with NeoVim
let sharedrc = '~/.config/nvim/sharedrc.vim'
exec "source " . sharedrc

colorscheme catppuccin-mocha
" Remove background so that terminal transparency can be respected
highlight Normal guibg=NONE ctermbg=NONE

