#!/bin/bash

# Requires NerdFont for Symbols
font="JetBrainsMono"

cheatsheet=(
    --title="LeafBoat Sway Keybindings:"
    --no-buttons
    --geometry=1200x640
    --list
    --no-click
    --no-selection
    --column="<span font='$font Bold 18'>Function</span>"
    --column="<span font='$font Bold 18'>Binding</span>"
    --column=""
    --column="<span font='$font Bold 18'>Function</span>"
    --column="<span font='$font Bold 18'>Binding</span>"
    --column-align=ccccc
    --header-align=ccccc
    "<span font='$font 16' foreground='#808080'>GENERAL</span>"
    ""
    ""
    "<span font='$font 16' foreground='#808080'>LAUNCHERS AND MENUS</span>"
    ""    
    "<span font='$font 14'>Mod Key</span>"
    "<span font='$font 18'></span>"
    ""
    "<span font='$font 14'>Application Launcher</span>"
    "<span font='$font 14'> + </span><span font='$font 18'>󰯴</span>"
    "<span font='$font 14'>Change Window Focus</span>"
    "<span font='$font 14'> + </span><span font='$font 18'>󰰀 󰰆 󰰉 󰰌</span>"
    ""
    "<span font='$font 14'>Power Menu</span>"
    "<span font='$font 14'> + Shift + </span><span font='$font 18'>󰯷</span>"
    "<span font='$font 14'>Close Window</span>"
    "<span font='$font 14'> + Shift + </span><span font='$font 18'>󰰛</span>"
    ""
    "<span font='$font 14'>Activities Overview</span>"
    "<span font='$font 14'> + </span><span font='$font 18'>󰰘</span>"
    "<span font='$font 14'>Move Window</span>"
    "<span font='$font 14'> + Shift + </span><span font='$font 18'>󰰀 󰰆 󰰉 󰰌</span>"
    ""
    "<span font='$font 16' foreground='#808080'>SCREENSHOTS</span>"
    ""
    "<span font='$font 14'>Move Window with Mouse</span>"
    "<span font='$font 14'> + 󰍽</span>"
    ""
    "<span font='$font 14'>Screenshot</span>"
    "<span font='$font 14'>PrtScn</span>"
    "<span font='$font 14'>Resize Window</span>"
    "<span font='$font 14'> + </span><span font='$font 18'>󰜳 󰜰 󰜹 󰜶</span>"
    ""
    "<span font='$font 14'>Screenshot Window</span>"
    "<span font='$font 14'>Ctrl + PrtScn</span>"
    "<span font='$font 14'>Resize with Right Click</span>"
    "<span font='$font 14'> + 󰍽</span>"
    ""
    "<span font='$font 14'>Screenshot Display</span>"
    "<span font='$font 14'>Shift + PrtScn</span>"
    "<span font='$font 14'>Switch to Workspace</span>"
    "<span font='$font 14'> + </span><span font='$font 18'>󰎦 󰎩 󰎬 󰎮</span><span font='$font 14'> ...</span>"
    ""
    "<span font='$font 16' foreground='#808080'>CLIPBOARD MANAGER</span>"
    ""
    "<span font='$font 14'>Send to Workspace</span>"
    "<span font='$font 14'> + Shift + </span><span font='$font 18'>󰎦 󰎩 󰎬 󰎮</span><span font='$font 14'> ...</span>"
    ""
    "<span font='$font 14'>Cliphist</span>"
    "<span font='$font 14'> + Ctrl + </span><span font='$font 18'>󰰪</span>"
    "<span font='$font 14'>Toggle Floating/Tiling</span>"
    "<span font='$font 14'> + Shift + Space</span>"
    ""
    "<span font='$font 14'>Delete Cliphist Entry</span>"
    "<span font='$font 14'> + Ctrl + </span><span font='$font 18'>󰰰</span>"
    "<span font='$font 14'>Toggle Fullscreen</span>"
    "<span font='$font 14'> + </span><span font='$font 18'>󰰶</span>"
    ""
    "<span font='$font 16' foreground='#808080'>APPLICATION SHORTCUTS</span>"
    ""
    "<span font='$font 16' foreground='#808080'>SCRATCHPAD</span>"
    ""
    ""
    "<span font='$font 14'>Terminal</span>"
    "<span font='$font 14'> + Enter</span>"
    "<span font='$font 14'>Send to Scratchpad</span>"
    "<span font='$font 14'> + Shift + </span><span font='$font 18'>󰛲</span>"
    ""
    "<span font='$font 14'>File Explorer</span>"
    "<span font='$font 14'> + </span><span font='$font 18'>󰰒</span>"
    "<span font='$font 14'>Next Scratchpad Window</span>"
    "<span font='$font 14'> + </span><span font='$font 18'>󰛲</span>"
    ""
    "<span font='$font 14'>Web Browser</span>"
    "<span font='$font 14'> + </span><span font='$font 18'>󰰕</span>"
    ""
)

yad --close-on-unfocus "${cheatsheet[@]}"
